language: node_js
sudo: required
dist: trusty
node_js:
  - lts/*
cache:
  directories:
  - node_modules
git:
  depth: 1
install:
  - npm i
before_script:
  - npm run lint
  - npm test
script:
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: hAUOAUZvLMKrdJecEC0FB5fVRKXMtQyapKMrY3YxsxInn8xPgCj6LvlAJdhmQCntrSBFC045+oalN/reAmaf3tIzVwtGCsoVMUiXOjbxnrkAXXBc6yHMHniHaatEUIT3IDJCCxDqLglkQlaf0BbRn0WWBBEQSjx4KJo3YxJ8dMbhx8itCcC36/WNMrodm2y7DPVMUpo7ks+2ZOMqVq2M89XqETwHlZynWS03mo9K4G9nHgFm5hiw2ch3KFQfbdvKMBr0tr20IYmvDmNfL//57KmvBHCnKuuPYh1gXjtc35Ju3C7eHFM6g7AHFgEf+28/DG2O3OxP6C+b3CxqILFuH4zYmT6tKikk/H6y8HSuCe+yH18AGbg6gDxQMFsPtFkXpfoU9wz3xoHRErXQ3M21W5Duet+oORWc/5QUQitryU1z0zARNyYCWj/XQoPQSlc9CAVzJGhQZEf1eQgDaQofbzrf6YBXI3yJw1GM6dA/uCCw2KfTFox7IDF8gczHhUyY+2SjZNVsCGlhQpCeCQAEAV/djJS1LUfi0GbJvML7YdKzxdFCWgpBJ8EofCF95PJ4/5DvDcL5BYGTTLhhyvqILm9IhazvvBwPjPMniFVq8oRng7NvXes48O8sGH5J89UDxGNEQSNBywVU+I2FhtHPCF0EtOBqlluTrZRM3WTOtw0=
